const medicalConditions = [
  { value: 'diabetes', label: 'Diabetes' },
  { value: 'hypertension', label: 'Hypertension' },
  { value: 'asthma', label: 'Asthma' },
  { value: 'heart_disease', label: 'Heart Disease' },
  { value: 'stroke', label: 'Stroke' },
  { value: 'cancer', label: 'Cancer' },
  { value: 'epilepsy', label: 'Epilepsy' },
  { value: 'kidney_disease', label: 'Kidney Disease' },
  { value: 'liver_disease', label: 'Liver Disease' },
  { value: 'none', label: 'None' },
  { value: 'tuberculosis', label: 'Tuberculosis' },
  { value: 'pneumonia', label: 'Pneumonia' },
  { value: 'bronchitis', label: 'Bronchitis' },
  { value: 'obesity', label: 'Obesity' },
  { value: 'arthritis', label: 'Arthritis' },
  { value: 'gout', label: 'Gout' },
  { value: 'chronic_kidney_disease', label: 'Chronic Kidney Disease' },
  { value: 'parkinson', label: 'Parkinson’s Disease' },
  { value: 'multiple_sclerosis', label: 'Multiple Sclerosis' },
  { value: 'alzheimer', label: 'Alzheimer’s Disease' },
  { value: 'hepatitis', label: 'Hepatitis' },
  { value: 'leukemia', label: 'Leukemia' },
  { value: 'anemia', label: 'Anemia' },
  { value: 'blood_pressure', label: 'Blood Pressure Disorders' },
  { value: 'thyroid_disease', label: 'Thyroid Disease' },
  { value: 'chronic_pain', label: 'Chronic Pain' },
  { value: 'mental_health', label: 'Mental Health Issues' },
  { value: 'autism', label: 'Autism Spectrum Disorder' },
  { value: 'depression', label: 'Depression' },
  { value: 'anxiety', label: 'Anxiety Disorders' },
  { value: 'schizophrenia', label: 'Schizophrenia' },
  { value: 'bipolar', label: 'Bipolar Disorder' },
  { value: 'dementia', label: 'Dementia' },
  { value: 'sickle_cell', label: 'Sickle Cell Anemia' },
  { value: 'cystic_fibrosis', label: 'Cystic Fibrosis' },
  { value: 'HIV', label: 'HIV/AIDS' },
  { value: 'hemophilia', label: 'Hemophilia' },
  { value: 'lupus', label: 'Lupus' },
  { value: 'vitamin_deficiency', label: 'Vitamin Deficiencies' },
  { value: 'migraines', label: 'Migraines' }
];

module.exports = { medicalConditions };
